
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "arangodbclient/handler.zep.h"
#include "arangodbclient/document.zep.h"
#include "arangodbclient/exception.zep.h"
#include "arangodbclient/documenthandler.zep.h"
#include "arangodbclient/adminhandler.zep.h"
#include "arangodbclient/aqluserfunction.zep.h"
#include "arangodbclient/batch.zep.h"
#include "arangodbclient/batchpart.zep.h"
#include "arangodbclient/bindvars.zep.h"
#include "arangodbclient/clientexception.zep.h"
#include "arangodbclient/collection.zep.h"
#include "arangodbclient/collectionhandler.zep.h"
#include "arangodbclient/connectexception.zep.h"
#include "arangodbclient/connection.zep.h"
#include "arangodbclient/connectionoptions.zep.h"
#include "arangodbclient/cursor.zep.h"
#include "arangodbclient/database.zep.h"
#include "arangodbclient/defaultvalues.zep.h"
#include "arangodbclient/edge.zep.h"
#include "arangodbclient/edgedefinition.zep.h"
#include "arangodbclient/edgehandler.zep.h"
#include "arangodbclient/endpoint.zep.h"
#include "arangodbclient/export.zep.h"
#include "arangodbclient/exportcursor.zep.h"
#include "arangodbclient/foxxhandler.zep.h"
#include "arangodbclient/graph.zep.h"
#include "arangodbclient/graphhandler.zep.h"
#include "arangodbclient/httphelper.zep.h"
#include "arangodbclient/httpresponse.zep.h"
#include "arangodbclient/querycachehandler.zep.h"
#include "arangodbclient/queryhandler.zep.h"
#include "arangodbclient/serverexception.zep.h"
#include "arangodbclient/statement.zep.h"
#include "arangodbclient/tracerequest.zep.h"
#include "arangodbclient/traceresponse.zep.h"
#include "arangodbclient/transaction.zep.h"
#include "arangodbclient/traversal.zep.h"
#include "arangodbclient/updatepolicy.zep.h"
#include "arangodbclient/urlhelper.zep.h"
#include "arangodbclient/urls.zep.h"
#include "arangodbclient/user.zep.h"
#include "arangodbclient/userhandler.zep.h"
#include "arangodbclient/valuevalidator.zep.h"
#include "arangodbclient/vertex.zep.h"
#include "arangodbclient/vertexhandler.zep.h"

#endif